# based on https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: ci

on:
  schedule:
    - cron: '0 10 * * 1'
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository == 'lsst-it/foreman_envsync'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
      - name: Build gem
        run: gem build *.gemspec
      - name: Publish gem to rubygems.org
        if: startsWith(github.ref, 'refs/tags/v')
        run: gem push *.gem
        env:
          GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_AUTH_TOKEN }}'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            lsstit/foreman_envsync
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LSSTIT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LSSTIT_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
